[theme]
primaryColor="#7393B3"  # Greenish accent, like Grok/GitHub dark
backgroundColor="#7393B3"  # Almost black background
secondaryBackgroundColor="#7393B3"  # Slightly lighter for cards/panels
textColor="#36454F"  
font="sans serif"