[theme]
# Base Theme: Crucial for a light theme
base = "light" 
primaryColor = "#7393B3" 
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#F7F9FB" 
textColor = "#333333" 

# Font Style: Use a modern, clean font
font = "sans serif"